package io.github.mpcoredeveloper.javaportico.emit;

import io.github.mpcoredeveloper.javaportico.mapping.NameSanitizer;
import io.github.mpcoredeveloper.javaportico.model.FieldKind;
import io.github.mpcoredeveloper.javaportico.model.FieldModel;
import io.github.mpcoredeveloper.javaportico.model.GrpcModel;
import io.github.mpcoredeveloper.javaportico.model.MessageModel;
import io.github.mpcoredeveloper.javaportico.model.RpcKind;
import io.github.mpcoredeveloper.javaportico.model.RpcModel;
import io.github.mpcoredeveloper.javaportico.model.ServiceModel;
import io.github.mpcoredeveloper.javaportico.model.WorkItem;

import java.util.List;

/**
 * Emits the gRPC-to-REST proxy ({@code {Service}Proxy}) that forwards unary calls to the legacy
 * OpenAPI service using the javaportico-runtime building blocks. JSON payloads are handled by
 * generated per-message readers/writers (Jackson-based, no reflection). Ported from SharpPortico's
 * ProxyEmitter.
 */
public final class ProxyJavaEmitter {

    private ProxyJavaEmitter() {
    }

    public static String emit(GrpcModel model, WorkItem item) {
        ServiceModel svc = model.services().get(0);
        CodeWriter w = new CodeWriter();
        w.line("// <auto-generated>");
        w.line("//     Generated by JavaPortico (OpenAPI to gRPC). Do not edit.");
        w.line("// </auto-generated>");
        w.line();
        w.line("package " + model.namespace() + ";");
        w.line();
        emitImports(w);
        w.block("public final class " + svc.name() + "Proxy extends " + svc.name() + "Grpc." + svc.name() + "ImplBase", () -> {
            w.line("private static final ObjectMapper JSON = new ObjectMapper();");
            w.line();
            w.line("private final ProxyOptions options;");
            w.line("private final IRestClient rest;");
            w.line("private final IProxyCache cache;");
            w.line("private final IKeyProvider keys;");
            w.line("private final IClientKeyValidator validator;");
            w.line("private final IProxyAuditLogger audit;");
            w.line();
            emitConstructor(w, svc);
            for (RpcModel rpc : svc.rpcMethods()) {
                if (rpc.kind() == RpcKind.UNARY) {
                    emitUnary(w, model, rpc, svc);
                }
            }
            emitLogAudit(w, svc);
            for (MessageModel msg : model.messages()) {
                emitSerialize(w, msg);
                emitParse(w, msg, model);
            }
        });
        return w.toString();
    }

    /**
     * Escapes a raw string so it is safe inside a double-quoted Java string literal.
     * OpenAPI-derived values (paths, parameter names, enum raw values) are embedded
     * into generated source; without escaping, a {@code "} or {@code \} in the spec
     * would break the literal boundary and allow injection of arbitrary source code
     * into the emitted proxy class.
     */
    public static String javaStringLiteral(String raw) {
        if (raw == null) return "";
        StringBuilder sb = new StringBuilder(raw.length() + 8);
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < 0x20) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        return sb.toString();
    }

    private static void emitImports(CodeWriter w) {
        w.line("import com.fasterxml.jackson.databind.JsonNode;");
        w.line("import com.fasterxml.jackson.databind.ObjectMapper;");
        w.line("import com.fasterxml.jackson.databind.node.ArrayNode;");
        w.line("import com.fasterxml.jackson.databind.node.ObjectNode;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.AuditEntry;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.ClientIdentity;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.GrpcStatusMapper;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.IClientKeyValidator;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.IKeyProvider;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.IProxyAuditLogger;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.IProxyCache;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.IRestClient;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.ProxyContext;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.ProxyOptions;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.RestRequest;");
        w.line("import io.github.mpcoredeveloper.javaportico.runtime.RestResponse;");
        w.line("import io.grpc.Metadata;");
        w.line("import io.grpc.Status;");
        w.line("import io.grpc.stub.StreamObserver;");
        w.line("import java.nio.charset.StandardCharsets;");
        w.line("import java.time.Instant;");
        w.line("import java.util.Base64;");
        w.line("import java.util.LinkedHashMap;");
        w.line("import java.util.Map;");
        w.line("import java.util.Objects;");
        w.line();
    }

    private static void emitConstructor(CodeWriter w, ServiceModel svc) {
        w.block("public " + svc.name() + "Proxy(ProxyOptions options, IRestClient rest, IProxyCache cache, IKeyProvider keys, IClientKeyValidator validator, IProxyAuditLogger audit)", () -> {
            w.line("this.options = Objects.requireNonNull(options, \"options\");");
            w.line("this.rest = Objects.requireNonNull(rest, \"rest\");");
            w.line("this.cache = cache;");
            w.line("this.keys = keys;");
            w.line("this.validator = validator;");
            w.line("this.audit = audit;");
        });
        w.line();
    }

    private static void emitLogAudit(CodeWriter w, ServiceModel svc) {
        w.block("private void logAudit(String rpcName, ClientIdentity identity, boolean cacheHit)", () -> {
            w.line("if (audit != null) {");
            w.openBlock();
            w.line("audit.log(new AuditEntry(\"" + svc.name() + "\", rpcName, identity.getKeyId(), identity.getRemoteAddress(), cacheHit, Instant.now(), null));");
            w.closeBlock();
            w.line("}");
        });
        w.line();
    }

    /** True-check expression for a request field. */
    private static String isSetExpr(FieldModel f) {
        String g = "request.get" + f.name() + "()";
        return switch (f.kind()) {
            case STRING, BYTES -> "!" + g + ".isEmpty()";
            case BOOL -> g;
            case INT32, INT64, UINT32, UINT64, FLOAT, DOUBLE -> g + " != 0";
            case ENUM -> "request.get" + f.name() + "Value() != 0";
            default -> "request.has" + f.name() + "()";
        };
    }

    /** String conversion expression for a request field. */
    private static String toStr(FieldModel f) {
        String g = "request.get" + f.name() + "()";
        return switch (f.kind()) {
            case STRING -> g;
            case BYTES -> "Base64.getEncoder().encodeToString(" + g + ".toByteArray())";
            case ENUM -> "String.valueOf(request.get" + f.name() + "Value())";
            case TIMESTAMP -> g + ".toString()";
            default -> "String.valueOf(" + g + ")";
        };
    }

    private static void emitUnary(CodeWriter w, GrpcModel model, RpcModel rpc, ServiceModel svc) {
        MessageModel reqMsg = model.messages().stream()
                .filter(m -> m.name().equals(rpc.requestType())).findFirst().orElse(null);
        MessageModel respMsg = model.messages().stream()
                .filter(m -> m.name().equals(rpc.responseType())).findFirst().orElse(null);
        String method = NameSanitizer.camel(rpc.name());
        boolean isRead = "GET".equalsIgnoreCase(rpc.httpMethod());

        w.line("@Override");
        w.block("public void " + method + "(" + rpc.requestType() + " request, StreamObserver<" + rpc.responseType() + "> responseObserver)", () -> {
            w.line("try {");
            w.openBlock();
            w.line("Metadata headers = ProxyContext.REQUEST_METADATA.get();");
            w.line("boolean isRead = " + isRead + ";");
            w.line("ClientIdentity identity = ProxyContext.readIdentity(headers, options.getClientKeyHeaderName());");
            w.line("boolean bypass = ProxyContext.parseBypass(headers, options.getBypassCacheMetadataKey());");
            w.line("String outboundKey = null;");
            w.block("switch (options.getClientKeyMode())", () -> {
                w.line("case FORWARD:");
                w.openBlock();
                w.line("outboundKey = identity.getKeyId();");
                w.line("break;");
                w.closeBlock();
                w.line("case OWN:");
                w.openBlock();
                w.line("if (validator == null || !validator.isValid(identity.getKeyId())) {");
                w.openBlock();
                w.line("responseObserver.onError(Status.UNAUTHENTICATED.withDescription(\"invalid client key\").asRuntimeException());");
                w.line("return;");
                w.closeBlock();
                w.line("}");
                w.line("outboundKey = keys != null ? keys.getApiKey(options.getApiKeyHeaderName()) : null;");
                w.line("break;");
                w.closeBlock();
                w.line("default:");
                w.openBlock();
                w.line("outboundKey = keys != null ? keys.getApiKey(options.getApiKeyHeaderName()) : null;");
                w.line("break;");
                w.closeBlock();
            });
            w.line();
            w.line("String path = \"" + javaStringLiteral(rpc.originalPath()) + "\";");
            w.line("Map<String, String> pathParams = new LinkedHashMap<>();");
            w.line("Map<String, String> queryParams = new LinkedHashMap<>();");
            w.line("Map<String, String> headersMap = new LinkedHashMap<>();");
            w.line("if (outboundKey != null) headersMap.put(options.getApiKeyHeaderName(), outboundKey);");
            w.line();

            if (reqMsg != null) {
                for (FieldModel f : reqMsg.fields()) {
                    if (f.name().startsWith("_") || f.kind() == FieldKind.MESSAGE) continue;
                    w.block("if (" + isSetExpr(f) + ")", () -> {
                        w.line("pathParams.put(\"" + javaStringLiteral(f.name()) + "\", " + toStr(f) + ");");
                        w.line("queryParams.put(\"" + javaStringLiteral(f.originalName()) + "\", " + toStr(f) + ");");
                    });
                }
            }
            w.line("byte[] body = null;");
            if (reqMsg != null) {
                FieldModel bodyField = reqMsg.fields().stream()
                        .filter(f -> f.name().equals("Body"))
                        .findFirst().orElse(null);
                if (bodyField != null) {
                    if (bodyField.kind() == FieldKind.MESSAGE) {
                        w.block("if (request.getBody() != null)", () -> {
                            w.line("body = JSON.writeValueAsBytes(serialize" + bodyField.typeName() + "(request.getBody()));");
                        });
                    } else if (bodyField.kind() == FieldKind.BYTES) {
                        w.block("if (request.getBody() != null && !request.getBody().isEmpty())", () -> {
                            w.line("body = request.getBody().toByteArray();");
                        });
                    }
                }
            }
            w.line();
            w.line("String cacheKey = \"" + svc.name() + "/" + rpc.name() + "/\" + path;");
            w.line("for (Map.Entry<String, String> e : queryParams.entrySet()) cacheKey += \",\" + e.getKey() + \"=\" + e.getValue();");
            w.line("boolean cacheHit = false;");
            w.line("byte[] cached = (!bypass && isRead && cache != null) ? cache.get(cacheKey) : null;");
            w.block("if (cached != null)", () -> {
                w.line("cacheHit = true;");
                w.line(rpc.responseType() + " hit = parse" + respMsg.name() + "(cached);");
                w.line("logAudit(\"" + rpc.name() + "\", identity, cacheHit);");
                w.line("responseObserver.onNext(hit);");
                w.line("responseObserver.onCompleted();");
                w.line("return;");
            });
            w.line();
            w.line("RestResponse resp;");
            w.block("try", () -> {
                w.line("resp = rest.send(new RestRequest(\"" + rpc.httpMethod() + "\", path, pathParams, queryParams, headersMap, body, \"application/json\"));");
            });
            w.line("catch (Exception ex) {");
            w.openBlock();
            w.line("responseObserver.onError(Status.INTERNAL.withDescription(String.valueOf(ex)).asRuntimeException());");
            w.line("return;");
            w.closeBlock();
            w.line("}");
            w.line("logAudit(\"" + rpc.name() + "\", identity, cacheHit);");
            w.block("if (resp.getStatusCode() < 200 || resp.getStatusCode() >= 300)", () -> {
                w.line("responseObserver.onError(GrpcStatusMapper.toStatus(resp.getStatusCode(), new String(resp.getBody(), StandardCharsets.UTF_8)).asRuntimeException());");
                w.line("return;");
            });
            w.line(rpc.responseType() + " result = parse" + respMsg.name() + "(resp.getBody());");
            w.line("if (isRead && !bypass && cache != null) cache.set(cacheKey, resp.getBody(), options.getCacheTtl());");
            w.line("responseObserver.onNext(result);");
            w.line("responseObserver.onCompleted();");
            w.closeBlock();
            w.line("} catch (Exception ex) {");
            w.openBlock();
            w.line("responseObserver.onError(Status.INTERNAL.withDescription(String.valueOf(ex)).asRuntimeException());");
            w.closeBlock();
            w.line("}");
        });
        w.line();
    }

    private static void emitSerialize(CodeWriter w, MessageModel msg) {
        w.block("private static JsonNode serialize" + msg.name() + "(" + msg.name() + " msg)", () -> {
            w.line("ObjectNode o = JSON.createObjectNode();");
            for (FieldModel f : msg.fields()) {
                if (f.name().startsWith("_")) continue;
                emitSerializeField(w, f);
            }
            w.line("return o;");
        });
        w.line();
    }

    private static void emitSerializeField(CodeWriter w, FieldModel f) {
        String key = "\"" + f.protoName() + "\"";
        String g = "msg.get" + f.name() + "()";
        switch (f.kind()) {
            case MESSAGE -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (" + f.typeName() + " item : msg.get" + f.name() + "List()) arr.add(serialize" + f.typeName() + "(item));");
                    });
                } else {
                    w.block("if (msg.has" + f.name() + "())", () -> {
                        w.line("o.set(" + key + ", serialize" + f.typeName() + "(" + g + "));");
                    });
                }
            }
            case ENUM -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (" + f.typeName() + " item : msg.get" + f.name() + "List()) arr.add(item.getNumber());");
                    });
                } else {
                    w.line("o.put(" + key + ", msg.get" + f.name() + "Value());");
                }
            }
            case STRING -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (String item : msg.get" + f.name() + "List()) arr.add(item);");
                    });
                } else {
                    w.line("o.put(" + key + ", " + g + ");");
                }
            }
            case BOOL -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (boolean item : msg.get" + f.name() + "List()) arr.add(item);");
                    });
                } else {
                    w.line("o.put(" + key + ", " + g + ");");
                }
            }
            case INT32, UINT32 -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (int item : msg.get" + f.name() + "List()) arr.add(item);");
                    });
                } else {
                    w.line("o.put(" + key + ", " + g + ");");
                }
            }
            case INT64, UINT64 -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (long item : msg.get" + f.name() + "List()) arr.add(item);");
                    });
                } else {
                    w.line("o.put(" + key + ", " + g + ");");
                }
            }
            case FLOAT, DOUBLE -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (double item : msg.get" + f.name() + "List()) arr.add(item);");
                    });
                } else {
                    w.line("o.put(" + key + ", " + g + ");");
                }
            }
            case BYTES -> {
                if (f.repeated()) {
                    w.block("if (msg.get" + f.name() + "Count() > 0)", () -> {
                        w.line("ArrayNode arr = o.putArray(" + key + ");");
                        w.line("for (com.google.protobuf.ByteString item : msg.get" + f.name() + "List()) arr.add(Base64.getEncoder().encodeToString(item.toByteArray()));");
                    });
                } else {
                    w.line("o.put(" + key + ", Base64.getEncoder().encodeToString(" + g + ".toByteArray()));");
                }
            }
            case TIMESTAMP -> {
                if (!f.repeated()) {
                    w.line("o.put(" + key + ", com.google.protobuf.util.Timestamps.toString(" + g + "));");
                }
            }
        }
    }

    private static void emitParse(CodeWriter w, MessageModel msg, GrpcModel model) {
        w.block("private static " + msg.name() + " parse" + msg.name() + "(byte[] body)", () -> {
            w.line("if (body == null || body.length == 0) return " + msg.name() + ".newBuilder().build();");
            w.block("try", () -> {
                w.line("return parse" + msg.name() + "(JSON.readTree(body));");
            });
            w.line("catch (Exception ex) {");
            w.openBlock();
            w.line("throw new RuntimeException(ex);");
            w.closeBlock();
            w.line("}");
        });
        w.line();
        w.block("private static " + msg.name() + " parse" + msg.name() + "(JsonNode el)", () -> {
            w.line(msg.name() + ".Builder b = " + msg.name() + ".newBuilder();");
            w.line("if (el != null && !el.isNull()) {");
            w.openBlock();
            w.block("if (el.isObject())", () -> {
                for (FieldModel f : msg.fields()) {
                    if (f.name().startsWith("_")) continue;
                    emitParseField(w, f, model);
                }
            });
            emitRootFallback(w, msg);
            w.closeBlock();
            w.line("}");
            w.line("return b.build();");
        });
        w.line();
    }

    private static void emitRootFallback(CodeWriter w, MessageModel msg) {
        List<FieldModel> nonSentinel = msg.fields().stream()
                .filter(f -> !f.name().startsWith("_"))
                .toList();
        if (nonSentinel.size() == 1) {
            FieldModel single = nonSentinel.get(0);
            if (single.kind() == FieldKind.MESSAGE) {
                if (single.repeated()) {
                    w.block("if (el.isArray())", () -> {
                        w.line("for (JsonNode itemEl : el) b.add" + single.name() + "(parse" + single.typeName() + "(itemEl));");
                    });
                } else {
                    w.block("if (el.isObject() && !b.has" + single.name() + "())", () -> {
                        w.line("b.set" + single.name() + "(parse" + single.typeName() + "(el));");
                    });
                }
            }
        }
    }

    private static void emitParseField(CodeWriter w, FieldModel f, GrpcModel model) {
        String key = "\"" + f.protoName() + "\"";
        String get = "el.get(" + key + ")";
        String set = "b.set" + f.name();
        String add = "b.add" + f.name();
        switch (f.kind()) {
            case STRING -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "(item.asText());");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(" + get + ".asText());");
                    });
                }
            }
            case INT32, UINT32 -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "(item.asInt());");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(" + get + ".asInt());");
                    });
                }
            }
            case INT64, UINT64 -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "(item.asLong());");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(" + get + ".asLong());");
                    });
                }
            }
            case FLOAT, DOUBLE -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "((float) item.asDouble());");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "((float) " + get + ".asDouble());");
                    });
                }
            }
            case BOOL -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "(item.asBoolean());");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(" + get + ".asBoolean());");
                    });
                }
            }
            case BYTES -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "(com.google.protobuf.ByteString.copyFrom(Base64.getDecoder().decode(item.asText())));");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(com.google.protobuf.ByteString.copyFrom(Base64.getDecoder().decode(" + get + ".asText())));");
                    });
                }
            }
            case TIMESTAMP -> {
                if (!f.repeated()) {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(com.google.protobuf.util.Timestamps.parse(" + get + ".asText()));");
                    });
                }
            }
            case MESSAGE -> {
                if (f.repeated()) {
                    w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                        w.line("for (JsonNode item : " + get + ") " + add + "(parse" + f.typeName() + "(item));");
                    });
                } else {
                    w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                        w.line(set + "(parse" + f.typeName() + "(" + get + "));");
                    });
                }
            }
            case ENUM -> {
                io.github.mpcoredeveloper.javaportico.model.EnumModel enumModel = model.enums().stream()
                        .filter(e -> e.name().equals(f.typeName()))
                        .findFirst().orElse(null);
                if (enumModel != null) {
                    if (f.repeated()) {
                        w.block("if (" + get + " != null && " + get + ".isArray())", () -> {
                            w.line("for (JsonNode item : " + get + ") {");
                            w.openBlock();
                            w.line("if (item.isNumber()) {");
                            w.openBlock();
                            w.line(add + "Value(item.asInt());");
                            w.closeBlock();
                            w.line("} else if (item.isTextual()) {");
                            w.openBlock();
                            w.line("String s = item.asText();");
                            boolean first = true;
                            for (io.github.mpcoredeveloper.javaportico.model.EnumValueModel ev : enumModel.values()) {
                                String cond = first ? "if" : "else if";
                                w.line(cond + " (s.equalsIgnoreCase(\"" + javaStringLiteral(ev.rawName()) + "\")) { " + add + "(" + f.typeName() + "." + NameSanitizer.toProtoEnumName(ev.name()) + "); }");
                                first = false;
                            }
                            w.closeBlock();
                            w.line("}");
                            w.closeBlock();
                            w.line("}");
                        });
                    } else {
                        w.block("if (" + get + " != null && !" + get + ".isNull())", () -> {
                            w.line("if (" + get + ".isNumber()) {");
                            w.openBlock();
                            w.line(set + "Value(" + get + ".asInt());");
                            w.closeBlock();
                            w.line("} else if (" + get + ".isTextual()) {");
                            w.openBlock();
                            w.line("String s = " + get + ".asText();");
                            boolean first = true;
                            for (io.github.mpcoredeveloper.javaportico.model.EnumValueModel ev : enumModel.values()) {
                                String cond = first ? "if" : "else if";
                                w.line(cond + " (s.equalsIgnoreCase(\"" + javaStringLiteral(ev.rawName()) + "\")) { " + set + "(" + f.typeName() + "." + NameSanitizer.toProtoEnumName(ev.name()) + "); }");
                                first = false;
                            }
                            w.closeBlock();
                            w.line("}");
                        });
                    }
                }
            }
        }
    }
}
